<?php
$_product = $block->getProduct();
$shipping = $_product->getData('shipping');
$product_data = $_product->getData('product_data');
$delivery_date = $_product->getData('delivery_date');
?>
<div class="product-info-custom">
<?php if ($shipping): ?>
    <p>Shipping: <?= $block->escapeHtml($shipping) ?></p>
<?php endif; ?>
<?php if ($product_data): ?>
    <p>Product Details: <?= $block->escapeHtml($product_data) ?></p>
<?php endif; ?>
<?php if ($delivery_date): ?>
    <p>Delivery Date: <?= $block->escapeHtml($delivery_date) ?></p>
<?php endif; ?>
</div>
