<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * Top menu for store
 *
 * @var $block \Magento\Theme\Block\Html\Topmenu
 */

?>
<header>
    <div id="custom-header-id" class="container-fluid inner-header">
        <div class="row no-margin">
            <div class="col-lg-3 col-md-3">
                <div class="logo">
                    <?php echo $block->getChildHtml("logo"); ?>
                </div>
            </div>           
            <div class="col-lg-7 col-md-7">
                <?php echo $block->getChildHtml("topSearch"); ?>      
            </div>
            <div class="col-lg-2 text-right col-md-2">
                <a href="<?= $block->getUrl('customer/account/login'); ?>"><?= __('Sign in') ?></a>
                <?php echo $block->getChildHtml('minicart'); ?>
            </div>
        </div>
        <div class="nav-item">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-6 col-sm-12 col-xs-12">
                        <?php echo $this->getLayout()->createBlock("Magento\Theme\Block\Html\Topmenu")->setTemplate("Magento_Theme::html/topmenu.phtml")->toHtml(); ?>
                    </div>
                </div>
            </div>
        </div>
        <div>
        <?php echo $this->getChildHtml('breadcrumbs'); ?>
</div>
    </div>
</header>


